"""Unattended batches: the server drafts via MCP sampling and sends.

Everywhere else the split is deliberate -- the server decides *who*, the
client's model decides *what to say*. That needs a human-driven turn, which is
fine at a desk and useless on a schedule.

MCP sampling closes that gap without moving the model into the server. The
server asks the *client* for a completion (`ctx.sample`), so there is still no
API key here, no prompt weights, and no copy generated by this process --
only a request for one. A cron-style caller can therefore run a batch end to
end while every guard stays exactly where it was.

Nothing is relaxed for automation. The same evidence gate, the same daily cap,
the same global dedupe, the same free-channel-only default, and dry_run still
defaults to true. An unattended run is strictly more cautious than a manual one
because nobody is watching it.
"""

import json
import logging
import re
from typing import Any

from fastmcp import Context

from sales_nav_mcp.config import get_config
from sales_nav_mcp.outreach import build_compose_prompt, send_message
from sales_nav_mcp.store import get_store

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "You draft short, specific B2B outreach messages. You return JSON only, "
    "with keys subject, body and evidence_used. Every claim you make must be "
    "grounded in the lead record you are given; evidence_used lists the exact "
    "record fields you drew on. If you cannot ground a message in the data, "
    "return an empty subject and body rather than inventing something."
)

# The model is asked for JSON, but models wrap it in prose or fences often
# enough that being strict here would fail batches for no good reason.
_FENCE = re.compile(r"```(?:json)?\s*(.+?)\s*```", re.S)


def extract_draft(text: str) -> dict[str, Any] | None:
    """Pull {subject, body, evidence_used} out of a model response.

    Accepts a bare JSON object, a fenced block, or an object embedded in
    surrounding prose. Returns None when nothing usable is present -- the
    caller records that as a failure rather than sending a guess.
    """
    if not text:
        return None
    candidates = [text]
    fenced = _FENCE.search(text)
    if fenced:
        candidates.insert(0, fenced.group(1))
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end > start:
        candidates.append(text[start : end + 1])

    for candidate in candidates:
        try:
            parsed = json.loads(candidate)
        except (ValueError, TypeError):
            continue
        if not isinstance(parsed, dict):
            continue
        if "subject" not in parsed or "body" not in parsed:
            continue
        evidence = parsed.get("evidence_used")
        if isinstance(evidence, str):
            evidence = [evidence]
        return {
            "subject": str(parsed.get("subject") or ""),
            "body": str(parsed.get("body") or ""),
            "evidence_used": list(evidence or []),
        }
    return None


def lead_payload(record: dict[str, Any]) -> str:
    """The slice of a lead the drafting model is allowed to see."""
    keep = (
        "fullName",
        "firstName",
        "title",
        "companyName",
        "companyIndustry",
        "companyLocation",
        "geoRegion",
        "tenureCompanyMonths",
        "tenurePositionMonths",
        "seniorityTop",
        "summary",
        "positions",
    )
    return json.dumps({k: record.get(k) for k in keep if record.get(k)}, default=str)


async def run_batch(
    url_hash: str,
    campaign: str,
    ctx: Context,
    *,
    limit: int = 5,
    dry_run: bool = True,
) -> dict[str, Any]:
    """Draft and (unless dry_run) send for up to `limit` eligible leads."""
    config = get_config().outreach
    store = get_store()

    if build_compose_prompt("{}").startswith("Cannot draft"):
        return {
            "error": "no_offer_file",
            "considered": 0,
            "drafted": 0,
            "sent": 0,
            "dry_run": dry_run,
            "suggestion": (
                "OFFER_FILE is not configured, so there is nothing to say. Set "
                "it before running an unattended batch."
            ),
        }

    candidates = store.outreach_candidates(url_hash, campaign, limit=limit)
    if not candidates:
        return {
            "url_hash": url_hash,
            "campaign": campaign,
            # Same keys as a productive run: a caller should not have to branch
            # on the result shape just because nothing was pending.
            "considered": 0,
            "drafted": 0,
            "sent": 0,
            "dry_run": dry_run,
            "sending_enabled": config.enabled,
            "results": [],
            "suggestion": (
                "Nothing eligible. Run enrich_leads first, or everyone here has "
                "already been contacted."
            ),
        }

    results: list[dict[str, Any]] = []
    sent = 0
    drafted = 0

    for candidate in candidates:
        member_id = candidate["member_id"]
        record = None
        for rec in store.iter_records(url_hash, limit=100000):
            if rec.get("memberId") == member_id:
                record = rec
                break
        if record is None:
            results.append({"member_id": member_id, "outcome": "no_record"})
            continue

        prompt = build_compose_prompt(lead_payload(record))
        try:
            reply = await ctx.sample(prompt, system_prompt=SYSTEM_PROMPT)
            text = getattr(reply, "text", None) or str(reply)
        except Exception as e:  # noqa: BLE001 - one bad draft must not end the run
            logger.warning("sampling failed for %s", member_id, exc_info=True)
            store.log_event(
                "sample",
                ok=False,
                member_id=member_id,
                campaign=campaign,
                error=str(e)[:300],
            )
            results.append(
                {
                    "member_id": member_id,
                    "outcome": "sampling_failed",
                    "error": str(e)[:200],
                }
            )
            continue

        draft = extract_draft(text)
        store.log_event(
            "sample",
            ok=draft is not None,
            member_id=member_id,
            campaign=campaign,
            error=None if draft else "unparseable draft",
        )
        if draft is None:
            results.append({"member_id": member_id, "outcome": "unparseable_draft"})
            continue
        drafted += 1

        # Straight into the same send path a human would use: evidence gate,
        # dedupe, cap, channel check, two-phase commit. None of it is bypassed
        # just because a model wrote the words.
        verdict = await send_message(
            member_id,
            campaign,
            draft["subject"],
            draft["body"],
            evidence_used=draft["evidence_used"],
            dry_run=dry_run,
            url_hash=url_hash,
        )
        if verdict.get("sent"):
            sent += 1
        results.append(
            {
                "member_id": member_id,
                "full_name": verdict.get("full_name"),
                "outcome": "sent"
                if verdict.get("sent")
                else ("would_send" if verdict.get("would_send") else "rejected"),
                "subject": draft["subject"],
                "problems": verdict.get("problems") or [],
                "channel": verdict.get("channel"),
            }
        )
        if verdict.get("daily_cap_remaining") == 0 and not dry_run:
            results.append({"outcome": "stopped", "why": "daily cap reached"})
            break

    return {
        "url_hash": url_hash,
        "campaign": campaign,
        "considered": len(candidates),
        "drafted": drafted,
        "sent": sent,
        "dry_run": dry_run,
        "sending_enabled": config.enabled,
        "results": results,
        "suggestion": (
            f"Drafted {drafted} of {len(candidates)}, sent {sent}."
            if not dry_run
            else (
                f"Dry run: drafted {drafted} of {len(candidates)}, sent nothing. "
                "Review the drafts, then re-run with dry_run=false."
            )
        ),
    }
